# Generated by Django 4.2.30 on 2026-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_product_alter_deal_id_alter_order_id_alter_query_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Desktop PCs', 'Desktop PCs'), ('Computer Accessories', 'Computer Accessories'), ('Networking', 'Networking'), ('Storage Devices', 'Storage Devices'), ('Service Items', 'Service Items'), ('General', 'General')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Desktop PCs', 'Desktop PCs'), ('Computer Accessories', 'Computer Accessories'), ('Networking', 'Networking'), ('Storage Devices', 'Storage Devices'), ('Service Items', 'Service Items'), ('General', 'General')], default='General', max_length=100),
        ),
    ]
